databases:
  - name: cass_bot_ada
    databaseName: cass_bot_ada
    user: cass_bot_ada
    plan: free

services:
  - type: web
    name: cass_bot_ada
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cass_bot_ada
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default
      - key: XAI_API_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: CARDASCAN_API_KEY
        sync: false
      - key: BLOCKFROST_API_KEY
        sync: false
